# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_bot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rget_bot.proto\"0\n\x04Root\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x18\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x08.Nested1\"\xca\x01\n\x07Nested1\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x03\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\x12\x18\n\x06\x66ield9\x18\t \x01(\x0b\x32\x08.Nested2\x12\x0f\n\x07\x66ield10\x18\n \x01(\t\x12\x19\n\x07\x66ield13\x18\r \x01(\x0b\x32\x08.Nested3\x12\x19\n\x07\x66ield14\x18\x0e \x01(\x0b\x32\x08.Nested4\"Y\n\x07Nested2\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x03\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\"9\n\x07Nested3\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\"\t\n\x07Nested4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_bot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROOT']._serialized_start=17
  _globals['_ROOT']._serialized_end=65
  _globals['_NESTED1']._serialized_start=68
  _globals['_NESTED1']._serialized_end=270
  _globals['_NESTED2']._serialized_start=272
  _globals['_NESTED2']._serialized_end=361
  _globals['_NESTED3']._serialized_start=363
  _globals['_NESTED3']._serialized_end=420
  _globals['_NESTED4']._serialized_start=422
  _globals['_NESTED4']._serialized_end=431
# @@protoc_insertion_point(module_scope)
