# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invite.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cinvite.proto\"r\n\x06Invite\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x1e\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x0e.Invite.Nested\x1a\x38\n\x06Nested\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\t\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invite_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVITE']._serialized_start=16
  _globals['_INVITE']._serialized_end=130
  _globals['_INVITE_NESTED']._serialized_start=74
  _globals['_INVITE_NESTED']._serialized_end=130
# @@protoc_insertion_point(module_scope)
